    @extends('parent')

    @section("content")
    @include("component.grafik")
    @include("component.free-trial")
    @include("component.footer")
    @include("component.work-title")
    @include("component.work")
    @include("component.analysis")
    @include("component.pricing")
    @include("component.testimonial")
    @include("component.costumer")
    @include("component.navbar")
    @include("component.hero")
    @endsection